{{- if .Values.ingressRoute.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "kube-app-manager.fullname" . }}-redirect-https
  labels:
    app.kubernetes.io/name: {{ include "kube-app-manager.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
