apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: webendpoints.apps.kovko.top
spec:
  group: apps.kovko.top
  scope: Cluster
  names:
    kind: WebEndpoint
    plural: webendpoints
    singular: webendpoint
    shortNames:
      - wep
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - name
                - description
                - url
                - icon
              properties:
                name:
                  type: string
                  minLength: 1
                description:
                  type: string
                  minLength: 1
                url:
                  type: string
                  minLength: 1
                icon:
                  type: string
                  minLength: 1
      additionalPrinterColumns:
        - name: Name
          type: string
          jsonPath: .spec.name
        - name: URL
          type: string
          jsonPath: .spec.url
