replicaCount: 1

image:
  repository: hocikto19/kube-app-manager
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

service:
  type: ClusterIP
  port: 8080

ingressRoute:
  enabled: true
  host: apps.example.local
  webEntryPoint: web
  websecureEntryPoint: websecure
  tls:
    enabled: true
    secretName: ""

certManager:
  enabled: false
  issuerRef:
    name: ""
    kind: ClusterIssuer
    group: cert-manager.io
  additionalDnsNames: []
  duration: ""
  renewBefore: ""

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

resources: {}
